// Event-driven recovery: each birth chooses its geometry from the living tree.
// Existing wood and the v3 design vocabulary are never regenerated by a cut.
import {pointOn,sample} from '../v1/model.mjs';
import {branchFamily,CUT_MODEL} from '../../pruning-model.mjs';
import {recoveryShape} from './recovery-shape.mjs';
import {NATURAL_GROWTH,NATURAL_GROWTH_POLICIES,GRADUAL_GROWTH_POLICIES,SPACE_GROWTH_POLICIES,WHOLE_TREE_GROWTH_POLICIES} from './natural-growth.mjs';
import {growthEnvironment,compareGrowthSites,chooseHeightSite} from './growth-space.mjs';
import {profile} from '../v2/growth.mjs';

const HOUR=3600000;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smooth=v=>{v=clamp(v);return v*v*(3-2*v);};
export function branchLevels(nodes){
 const byId=new Map(nodes.map(n=>[n.id,n])),levels=new Map();
 function level(n){if(levels.has(n.id))return levels.get(n.id);const parent=byId.get(n.parent);
  const value=n.role==='primary'?1:n.role==='trunk'||n.role==='bough'?0:parent&&level(parent)>0?level(parent)+1:0;
  levels.set(n.id,value);return value;
 }
 nodes.forEach(level);return levels;
}
function attachment(parent,node){
 if(Number.isFinite(node.attachment))return node.attachment;
 let best=.5,distance=Infinity;
 for(let i=0;i<=100;i++){const q=pointOn(parent,i/100),d=Math.hypot(q.x-node.x,q.y-node.y);if(d<distance){distance=d;best=i/100;}}
 return best;
}

export function recoveryPlan(scaffold,record,at,layout=scaffold){
 const seed=record.config.seed,levels=branchLevels(scaffold.nodes);
 const live=new Map(scaffold.nodes.map(n=>[n.id,{...n,pruningLevel:levels.get(n.id)}]));
 let natural=NATURAL_GROWTH_POLICIES.includes(record.config.growthPolicy)&&Number.isFinite(record.createdAt);
 let gradual=natural&&GRADUAL_GROWTH_POLICIES.includes(record.config.growthPolicy);
 let spaceFirst=natural&&SPACE_GROWTH_POLICIES.includes(record.config.growthPolicy);
 let wholeTreeGrowth=natural&&WHOLE_TREE_GROWTH_POLICIES.includes(record.config.growthPolicy);
 let descendingHeight=natural&&record.config.growthPolicy===NATURAL_GROWTH;
 const wounds=[];
 const original=new Map(live),zones=[],zoneFor=new Map(),jobs=new Map();let serial=0,intervals=natural;
 const naturalStart=Number.isFinite(record.createdAt)?record.createdAt+Math.ceil(profile(record).days*24)*HOUR:0;
 const schedules=new Map();
 // Group along the protected axis, not screen height (including cascades).
 const layoutNodes=new Map(layout.nodes.map(n=>[n.id,n]));
 const supportIndex=new Map(layout.nodes.filter(n=>n.role==='trunk'||n.role==='bough').map((n,i)=>[n.id,i]));
 const primaries=layout.nodes.filter(n=>n.role==='primary').sort((a,b)=>(supportIndex.get(a.parent)-supportIndex.get(b.parent))||attachment(layoutNodes.get(a.parent),a)-attachment(layoutNodes.get(b.parent),b)||a.id.localeCompare(b.id));
 const count=Math.min(record.config.preset==='literati'?2:3,primaries.length);
 for(let i=0;i<count;i++)zones.push({id:`zone-${i}`,supports:[],members:[],target:0});
 for(const [i,n]of primaries.entries()){
  const zone=zones[Math.min(count-1,Math.floor(i*count/primaries.length))];zone.members.push(n);zoneFor.set(n.id,zone.id);
  zone.supports.push({parentId:n.parent,t:attachment(layoutNodes.get(n.parent),n),referenceId:n.id});
 }
 for(const zone of zones){zone.target=Math.min(3,zone.members.length);zone.low=Math.max(1,zone.target-1);}
 // A small, seeded surplus: at most one extra primary in the whole tree,
 // and a third secondary on roughly one third of its trained branch families.
 const extraZone=record.config.preset!=='literati'&&primaries.length>=4?zones[Math.floor(sample(seed,'natural','region')*zones.length)]?.id:null;
 const extraFamilies=new Set([...primaries].sort((a,b)=>sample(seed,a.id,'surplus')-sample(seed,b.id,'surplus')||a.id.localeCompare(b.id)).slice(0,Math.max(1,Math.round(primaries.length*.3))).map(n=>n.id));
 for(const n of live.values()){let parent=n;while(parent&&parent.pruningLevel>1)parent=live.get(parent.parent);n.zoneId=zoneFor.get(parent?.id?.replace(/^regrow:\d+:/,''));}
 const recovery=time=>(record.waterings??[]).reduce((sum,w)=>sum+(w.at<=at&&w.at<time?(w.recoveryHours??0)*HOUR:0),0);
 const end=at+recovery(Infinity),removed=new Set();
 const events=(record.cuts??[]).filter(c=>Number.isFinite(c.at)&&c.at<=at).map((c,i)=>({...c,at:c.at+recovery(c.at),seq:c.seq??i})).sort((a,b)=>a.at-b.at||a.seq-b.seq);
 const children=id=>[...live.values()].filter(n=>n.parent===id);
 const total=job=>job.parentId?children(job.parentId).length:[...live.values()].filter(n=>n.pruningLevel===1&&(job.wholeTree||n.zoneId===job.zoneId)).length;
 function limits(job){
  if(job.wholeTree)return zones.reduce((sum,z)=>{const range=limits({zoneId:z.id});for(const k of ['min','ideal','max'])sum[k]+=range[k];return sum;},{min:0,ideal:0,max:0});
  const parent=live.get(job.parentId),zone=zones.find(z=>z.id===job.zoneId),min=parent?.pruningLevel===2?0:1;
  if(!natural)return {min,max:job.parentId?2:Math.max(2,zone.target)};
  const reference=parent?.growthReference??parent?.id;
  const ideal=parent?.pruningLevel===2?Math.min(2,[...layoutNodes.values()].filter(n=>n.parent===reference).length):parent?2:zone.members.length;
  const extra=parent?(parent.pruningLevel===1&&extraFamilies.has(reference)?1:0):(zone.id===extraZone?1:0);
  return {min:gradual&&!parent?Math.max(1,ideal-1):min,ideal,max:ideal+extra};
 }
 function schedule(job,time){
  const {min,max,ideal=max}=limits(job),count=total(job);
  const vigor=gradual?Math.max(.5,1.6/(1+Math.max(0,time-naturalStart)/(72*HOUR))):1;
  const chance=gradual?(count<min?.7:Math.min(.7,vigor*(count>=ideal?(job.parentId?.045:.035):.3*(ideal-count)/Math.max(1,ideal-min)))):
   count<min?.55:count>=ideal?(job.parentId?.035:.025):.25*(ideal-count)/Math.max(1,ideal-min);
  const draw=schedules.get(job.key)??0;schedules.set(job.key,draw+1);
  const random=sample(seed,`population:${job.key}:${draw}`,'wait');
  // Equivalent to a Bernoulli trial every two biological hours. Sampling the
  // first success skips failed ticks and remains independent of render cadence,
  // request UUIDs and absolute wall time (including cheat rebases).
  const ticks=1+Math.floor(Math.log1p(-random)/Math.log1p(-chance));
  Object.assign(job,{min,target:max,chance,stochastic:true,styled:true,next:time+ticks*2*HOUR});
 }
 function queue(key,scope,time,target){if(!jobs.has(key)){
  const job={key,...scope,target,started:time,next:time+HOUR};if(intervals&&total(job)>=limits(job).max)return;
  jobs.set(key,job);if(intervals)schedule(job,time);
 }}
 function checkIntervals(time){
  if(wholeTreeGrowth&&zones.length){const scope={wholeTree:true,zoneId:zones[0].id};if(total(scope)<limits(scope).max)queue('primary',scope,Math.max(time,naturalStart),limits(scope).max);}
  else for(const zone of zones){const scope={zoneId:zone.id};if(total(scope)<limits(scope).max)queue(zone.id,scope,Math.max(time,natural?naturalStart:time),limits(scope).max);}
  for(const parent of live.values())if([1,2].includes(parent.pruningLevel)){
   const scope={parentId:parent.id,zoneId:parent.zoneId};
   if(total(scope)<limits(scope).max)queue(parent.id,scope,Math.max(time,parent.readyAt??(natural?naturalStart:time)),limits(scope).max);
  }
 }
 function check(time,affected){
  if(intervals){checkIntervals(time);return;}
  for(const zone of zones){const total=[...live.values()].filter(n=>n.pruningLevel===1&&n.zoneId===zone.id).length;
   if(total<zone.low)queue(zone.id,{zoneId:zone.id},time,zone.target);
  }
  if(affected){const parent=live.get(affected);if(parent&&parent.pruningLevel===1&&children(parent.id).length<2)queue(parent.id,{parentId:parent.id,zoneId:parent.zoneId},Math.max(time,parent.readyAt??time),2);}
 }
 function spawn(job,time,recoveryCut){
  const zone=zones.find(z=>z.id===job.zoneId),level=job.parentId?live.get(job.parentId).pruningLevel+1:1;
  const surplus=natural&&!recoveryCut&&total(job)>=limits(job).ideal;
  const key=`state-growth:${serial}`,r=(i,p)=>sample(seed,`${key}:${i}`,p);
  const modern=!!(recoveryCut||job.avoid||job.styled);
  const trunkSamples=modern?[...live.values()].filter(n=>n.pruningLevel===0).flatMap(n=>Array.from({length:25},(_,i)=>({...pointOn(n,i/24),radius:(n.width+(n.tipWidth-n.width)*i/24)/2}))):[];
  const recent=gradual?wounds.filter(w=>time-w.at<=72*HOUR).slice(-6):[];
  const avoided=recent.length?recent.map(w=>w.node):job.avoid?[job.avoid]:[];
  const cutSamples=avoided.flatMap(n=>Array.from({length:13},(_,i)=>pointOn(n,i/12)));
  const woodSamples=modern?[...live.values()].filter(n=>n.pruningLevel>0).map(n=>({id:n.id,points:Array.from({length:9},(_,i)=>({...pointOn(n,i/8),radius:(n.width+(n.tipWidth-n.width)*i/8)/2}))})):[];
  const environment=spaceFirst?growthEnvironment(live,layout,time):null;
  // Primary branch budgets belong to the whole tree. A cut opens capacity,
  // not a mandatory replacement site. Local caps still protect the silhouette.
  const available=job.wholeTree?zones.filter(z=>total({zoneId:z.id})<z.members.length+1):[zone];
  const supports=available.flatMap(z=>z.supports.map(s=>({...s,zoneId:z.id})));
  const heights=primaries.map(n=>n.y),top=Math.min(...heights),span=Math.max(1,Math.max(...heights)-top);
  const candidates=[];
  for(let i=0;i<(job.wholeTree?Math.max(32,supports.length*4):modern?32:16);i++){
   const support=job.parentId?null:job.wholeTree?supports[i%supports.length]:zone.supports[Math.floor(r(i,'support')*zone.supports.length)];
   const parent=live.get(job.parentId??support.parentId),t=job.parentId?(surplus?.32+r(i,'attach')*.54:.48+r(i,'attach')*.42):clamp(support.t+(r(i,'attach')-.5)*.16,.08,.96);
   const start=pointOn(parent,t);
   const parentReference=layoutNodes.get(parent.growthReference??parent.id)??parent;
   const referenceChildren=modern&&level>1?[...layoutNodes.values()].filter(n=>n.parent===parentReference.id):[];
   const model=modern?(level===1?layoutNodes.get(support.referenceId):referenceChildren[Math.floor(r(i,'model')*referenceChildren.length)]??parentReference):level===1?zone.members[Math.floor(r(i,'model')*zone.members.length)]:parent;
   const heading=Math.atan2(model.ey-model.y,model.ex-model.x),angle=heading+(r(i,'angle')-.5)*(recoveryCut?1.5:level===1?.9:1.3);
   const length=level===1?clamp(Math.hypot(model.ex-model.x,model.ey-model.y)*(.72+r(i,'length')*.25),recoveryCut?40:24,115):clamp(Math.hypot(parent.ex-parent.x,parent.ey-parent.y)*(.4+r(i,'length')*.15),recoveryCut?26:12,46);
   const shape=modern?recoveryShape({parent,reference:model,parentReference,t,level,preset:record.config.preset,random:p=>r(i,p),frame:scaffold.applicationFrame,root:scaffold.root,surplus}):null;
   const ex=shape?.ex??start.x+Math.cos(angle)*length,ey=shape?.ey??start.y+Math.sin(angle)*length;
   let space=80;for(const other of live.values()){if(other.id===parent.id||other.pruningLevel===0)continue;space=Math.min(space,Math.hypot(ex-other.ex,ey-other.ey));}
   const b=scaffold.applicationFrame,inside=ex>b.x+45&&ex<b.x+b.width-45&&ey>b.y+45&&ey<b.y+b.height-45;
   const aboveSoil=record.config.preset==='cascade'||ey<scaffold.root.y-20;
   // A replacement should emerge beyond the protected wood, not finish
   // concealed inside its silhouette. Preserve historical state-1 choices.
   const clearance=trunkSamples.length?Math.min(...trunkSamples.map(q=>Math.hypot(ex-q.x,ey-q.y)-q.radius)):0;
   // Prefer both a different attachment and a different growing direction.
   // Compare the outer shoot to the cut curve, not just its tip: nearby tips
   // alone miss branches that retrace the removed wood. This is a preference,
   // so a small parent can still recover when it has no distant attachment.
   const dx=ex-start.x,dy=ey-start.y;
   const curve=shape??{...start,ex,ey,cx1:start.x+dx*.32,cy1:start.y+dy*.26+2,cx2:start.x+dx*.72,cy2:start.y+dy*.8+2};
   const crown=modern?layout.clusters.filter(c=>c.pad===model.pad&&[c.x,c.y,c.rx,c.ry].every(Number.isFinite)):[];
   const bounds=crown.length?{left:Math.min(...crown.map(c=>c.x-c.rx))-12,right:Math.max(...crown.map(c=>c.x+c.rx))+12,
    top:Math.min(...crown.map(c=>c.y-c.ry))-12,bottom:Math.max(...crown.map(c=>c.y+c.ry))+12}:null;
   const overflow=bounds?Math.hypot(Math.max(bounds.left-ex,0,ex-bounds.right),Math.max(bounds.top-ey,0,ey-bounds.bottom)):0;
   // Measure wood clearance along the shoot, not only at its endpoint.
   const ancestors=new Set();let ancestor=parent;while(ancestor){ancestors.add(ancestor.id);ancestor=live.get(ancestor.parent);}
   let woodRoom=20;
   if(modern)for(const u of [.4,.7,1]){const p=pointOn(curve,u);for(const wood of woodSamples){if(ancestors.has(wood.id))continue;
    for(const q of wood.points){const radius=q.radius+(shape?.width??1)/2,reach=woodRoom+radius,dx=p.x-q.x,dy=p.y-q.y;
     if(reach>0&&dx*dx+dy*dy<reach*reach)woodRoom=Math.min(woodRoom,Math.hypot(dx,dy)-radius);
    }
   }}
   const separation=cutSamples.length?[.35,.65,1].reduce((sum,t)=>{const p=pointOn(curve,t);return sum+Math.min(...cutSamples.map(q=>Math.hypot(p.x-q.x,p.y-q.y)));},0)/3:0;
   const rootDistance=avoided.length?Math.min(...avoided.map(n=>Math.hypot(start.x-n.x,start.y-n.y))):0;
   const relocation=avoided.length?clamp(separation,0,45)*(gradual?6:4)+clamp(rootDistance,0,30)*(gradual?2:1.5):0;
   const habitat=environment?.(curve);
   const habitatBand=habitat?Math.floor((clamp(woodRoom/20)*25+habitat.openness*25+habitat.light*40+clamp(space/80)*10)/5):0;
   // Prefer higher attachment sites only among comparably open, lit choices.
   // Cascades keep their descending architecture rather than chasing the top.
   const heightBand=wholeTreeGrowth?Math.floor(clamp((top+span-start.y)/span)*(record.config.preset==='cascade'?.8:record.config.preset==='windswept'?2:4)):0;
   candidates.push({parent,t,start,ex,ey,shape,model,woodRoom,space,habitat,habitatBand,heightBand,relocation,zoneId:support?.zoneId??zone.id,safe:inside&&aboveSoil&&clearance>=4&&overflow===0,
    score:space+r(i,'jitter')*4+(inside&&aboveSoil?0:-1000)+(modern?clamp(clearance,-80,30)*5+clamp(woodRoom,-30,20)*3-overflow*8:0)+relocation});
  }
  const c=descendingHeight?chooseHeightSite(candidates):candidates.sort(spaceFirst?compareGrowthSites:(a,b)=>(modern?Number(b.safe)-Number(a.safe):0)||b.score-a.score)[0],b=scaffold.applicationFrame;
  const ex=clamp(c.ex,b.x+45,b.x+b.width-45),ey=clamp(c.ey,b.y+45,record.config.preset==='cascade'?b.y+b.height-45:scaffold.root.y-25);
  const id=`sprout:${serial++}`,dx=ex-c.start.x,dy=ey-c.start.y;
  const width=clamp((c.parent.width+(c.parent.tipWidth-c.parent.width)*c.t)*.52,.9,level===1?9:4);
  const template=(modern?layout.clusters.find(n=>n.pad===c.model.pad):undefined)??scaffold.clusters.find(n=>n.pad===c.parent.pad)??scaffold.clusters.find(n=>n.pad===zone.members[0].pad)??scaffold.clusters[0];
  // Only this new shoot earns the establishment time. The tree's age and
  // existing shoots are unchanged, and the cut event makes this reproducible.
  const initialAgeHours=recoveryCut?12:0,durationHours=gradual?(level===1?8:6):(level===1?12:8);
  const node={id,key:id,parent:c.parent.id,role:level===1?'primary':'twig',pruningLevel:level,branchOrder:level,
   zoneId:c.zoneId,pad:template.pad,z:template.z,attachment:c.t,x:c.start.x,y:c.start.y,ex,ey,
   cx1:c.start.x+dx*.32,cy1:c.start.y+dy*.26+2,cx2:c.start.x+dx*.72,cy2:c.start.y+dy*.8+2,
   width,tipWidth:width*.32,...(c.shape?{...c.shape,growthReference:c.model.id}:{}),born:-100,duration:1,bornAt:time,readyAt:time+Math.max(0,durationHours-initialAgeHours)*HOUR,regrown:true,leafTemplate:template,
   ...(recoveryCut?{recoveryCut,initialAgeHours}:{} ),...(surplus?{surplus:true}:{})};
  live.set(id,node);
  if(level<3)queue(id,{parentId:id,zoneId:c.zoneId,...(modern?{styled:true}:{})},node.readyAt,2);
 }
 function advance(time){
  while(true){
   const job=[...jobs.values()].filter(j=>j.next<=time).sort((a,b)=>a.next-b.next||a.started-b.started||a.key.localeCompare(b.key))[0];if(!job)break;
   if(job.parentId&&!live.has(job.parentId)){jobs.delete(job.key);continue;}
   const current=total(job);
   if(current>=job.target){jobs.delete(job.key);continue;}
   const birth=job.next;spawn(job,birth);if(current+1>=job.target)jobs.delete(job.key);else if(job.stochastic)schedule(job,birth);else job.next+=2*HOUR;
  }
 }
 if(natural)checkIntervals(naturalStart);
 for(const cut of events){
  advance(cut.at);const node=live.get(cut.branchId);if(!node||![1,2].includes(node.pruningLevel))continue;
  if(['state-3','state-4','state-5','state-6','state-7',CUT_MODEL].includes(cut.model)&&(!intervals||(['state-4','state-5','state-6','state-7',CUT_MODEL].includes(cut.model)&&!natural)||(['state-5','state-6','state-7',CUT_MODEL].includes(cut.model)&&!gradual))){
   // Historical state-1/state-2 births keep their identities. Switch only at
   // the first new interaction, never retroactively before that cut.
   intervals=true;if(['state-4','state-5','state-6','state-7',CUT_MODEL].includes(cut.model))natural=true;if(['state-5','state-6','state-7',CUT_MODEL].includes(cut.model))gradual=true;jobs.clear();
  }
  if(['state-6','state-7',CUT_MODEL].includes(cut.model))spaceFirst=true;
  if(['state-7',CUT_MODEL].includes(cut.model)&&!wholeTreeGrowth){wholeTreeGrowth=true;for(const [key,job]of jobs)if(!job.parentId)jobs.delete(key);}
  if(cut.model===CUT_MODEL)descendingHeight=true;
  const family=branchFamily([...live.values()],node.id);for(const id of family){removed.add(id);live.delete(id);jobs.delete(id);}
  if(gradual){wounds.push({node,at:cut.at});if(wounds.length>6)wounds.shift();}
  check(cut.at,node.parent);
  if(gradual){
   const job=jobs.get(node.pruningLevel===1?(wholeTreeGrowth?'primary':node.zoneId):node.parent);
   if(job){
    job.avoid=node;
    // A deficit accelerates recovery, but never grants age or a visible branch
    // at the cut instant. Existing reservations are rescheduled from this cut.
    schedule(job,Math.max(cut.at,live.get(job.parentId)?.readyAt??cut.at));
   }
  }else if(['state-3','state-4'].includes(cut.model)||(!intervals&&cut.model==='state-2')){
   // One immediate replacement in the area this cut made sparse. Unrelated
   // pending jobs and finer descendants keep their ordinary schedule.
   const job=jobs.get(node.pruningLevel===1?node.zoneId:node.parent);
   if(job){
    // Retain this preference for the rest of this local recovery job too.
    // A later cut in the same region replaces it; unrelated regions are free.
    job.avoid=node;
    const parent=job.parentId&&live.get(job.parentId);
    const current=total(job),threshold=intervals?job.min:job.target;
    if(current<threshold&&(!parent||parent.pruningLevel===1)){
     spawn(job,cut.at,cut.id);
     if(current+1>=job.target)jobs.delete(job.key);else if(intervals)schedule(job,cut.at);else job.next=cut.at+2*HOUR;
    }
   }
  }
 }
 advance(end);
 const primaryRanges=wholeTreeGrowth&&zones.length?[{key:'primary',wholeTree:true,zoneId:zones[0].id,level:1}]:zones.map(zone=>({key:zone.id,zoneId:zone.id,level:1}));
 const ranges=intervals?[...primaryRanges,...[...live.values()].filter(n=>n.pruningLevel===1).map(n=>({key:n.id,parentId:n.id,zoneId:n.zoneId,level:2}))].map(scope=>({...scope,count:total(scope),...limits(scope)})):undefined;
 return {live,original,removed,jobs:[...jobs.values()],end,zones,ranges,gradual};
}

export function applyRecovery(tree,scaffold,record,at,layout=scaffold){
 const plan=recoveryPlan(scaffold,record,at,layout),levels=branchLevels(scaffold.nodes),mapped=new Map();
 tree.nodes=tree.nodes.filter(n=>!plan.removed.has(n.id)).map(n=>({...n,pruningLevel:levels.get(n.id)}));
 tree.clusters=tree.clusters.filter(c=>!plan.removed.has(c.node));tree.buds=tree.buds.filter(c=>!plan.removed.has(c.node));
 tree.nodes.forEach(n=>mapped.set(n.id,n));
 const scale=.55+.45*smooth(tree.progress),thickness=(.04+.96*tree.progress**1.3)*smooth(tree.progress/.018);
 for(const n of plan.live.values()){
  if(!Number.isFinite(n.bornAt))continue;
  const parent=mapped.get(n.parent);if(!parent)continue;
  const age=(plan.end-n.bornAt)/HOUR+(n.initialAgeHours??0);
  const durationHours=n.initialAgeHours?(n.pruningLevel===1?12:8):(n.readyAt-n.bornAt)/HOUR;
  const g=smooth(age/durationHours)*Math.min(1,parent.growth??1);
  const anchor=pointOn(parent,n.attachment),{leafTemplate,bornAt,readyAt,...properties}=n;
  const node={...properties,x:anchor.x,y:anchor.y,growth:g,width:n.width*thickness*(.15+.85*g),tipWidth:n.tipWidth*thickness*(.15+.85*g)};
  for(const [x,y]of [['cx1','cy1'],['cx2','cy2'],['ex','ey']]){node[x]=anchor.x+(n[x]-n.x)*scale*g;node[y]=anchor.y+(n[y]-n.y)*scale*g;}
  mapped.set(n.id,node);if(g<=0)continue;tree.nodes.push(node);
  const leafAmount=Math.min(smooth((age-3)/18),tree.progress**3);
  if(leafAmount>0){const size=Math.sqrt(leafAmount)*scale;tree.clusters.push({...leafTemplate,node:n.id,key:`leaf:${n.id}`,x:node.ex,y:node.ey-3*size,
   rx:Math.min(32,leafTemplate.rx)*size,ry:Math.min(22,leafTemplate.ry)*size,leafAmount,born:-100,duration:1,crownAge:clamp(age/96)});}
 }
 tree.recovery=plan.jobs.flatMap(job=>{
  const zone=plan.zones.find(z=>z.id===job.zoneId),support=job.parentId?{parentId:job.parentId,t:.7}:zone.supports[0],parent=mapped.get(support.parentId);
  if(!parent||parent.growth<=0)return [];
  const p=pointOn(parent,support.t);return [{key:job.key,node:parent.id,x:p.x,y:p.y,level:job.parentId?(parent.pruningLevel??1)+1:1,hours:Math.max(0,(job.next-plan.end)/HOUR),...(job.stochastic?{chance:job.chance,min:job.min,max:job.target}:{} )}];
 });
 if(plan.ranges)tree.branchRanges=plan.ranges;
 if(plan.gradual)tree.gradualGrowth=true;
 return tree;
}
