// Event-driven recovery: each birth chooses its geometry from the living tree.
// Existing wood and the v3 design vocabulary are never regenerated by a cut.
import {pointOn,sample} from '../v1/model.mjs';
import {branchFamily} from '../../pruning-model.mjs';

const HOUR=3600000;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smooth=v=>{v=clamp(v);return v*v*(3-2*v);};
export function branchLevels(nodes){
 const byId=new Map(nodes.map(n=>[n.id,n])),levels=new Map();
 function level(n){if(levels.has(n.id))return levels.get(n.id);const parent=byId.get(n.parent);
  const value=n.role==='primary'?1:n.role==='trunk'||n.role==='bough'?0:parent&&level(parent)>0?level(parent)+1:0;
  levels.set(n.id,value);return value;
 }
 nodes.forEach(level);return levels;
}
function attachment(parent,node){
 if(Number.isFinite(node.attachment))return node.attachment;
 let best=.5,distance=Infinity;
 for(let i=0;i<=100;i++){const q=pointOn(parent,i/100),d=Math.hypot(q.x-node.x,q.y-node.y);if(d<distance){distance=d;best=i/100;}}
 return best;
}

export function recoveryPlan(scaffold,record,at,layout=scaffold){
 const seed=record.config.seed,levels=branchLevels(scaffold.nodes);
 const live=new Map(scaffold.nodes.map(n=>[n.id,{...n,pruningLevel:levels.get(n.id)}]));
 const original=new Map(live),zones=[],zoneFor=new Map(),jobs=new Map();let serial=0;
 // Group along the protected axis, not screen height (including cascades).
 const layoutNodes=new Map(layout.nodes.map(n=>[n.id,n]));
 const supportIndex=new Map(layout.nodes.filter(n=>n.role==='trunk'||n.role==='bough').map((n,i)=>[n.id,i]));
 const primaries=layout.nodes.filter(n=>n.role==='primary').sort((a,b)=>(supportIndex.get(a.parent)-supportIndex.get(b.parent))||attachment(layoutNodes.get(a.parent),a)-attachment(layoutNodes.get(b.parent),b)||a.id.localeCompare(b.id));
 const count=Math.min(record.config.preset==='literati'?2:3,primaries.length);
 for(let i=0;i<count;i++)zones.push({id:`zone-${i}`,supports:[],members:[],target:0});
 for(const [i,n]of primaries.entries()){
  const zone=zones[Math.min(count-1,Math.floor(i*count/primaries.length))];zone.members.push(n);zoneFor.set(n.id,zone.id);
  zone.supports.push({parentId:n.parent,t:attachment(layoutNodes.get(n.parent),n)});
 }
 for(const zone of zones){zone.target=Math.min(3,zone.members.length);zone.low=Math.max(1,zone.target-1);}
 for(const n of live.values()){let parent=n;while(parent&&parent.pruningLevel>1)parent=live.get(parent.parent);n.zoneId=zoneFor.get(parent?.id?.replace(/^regrow:\d+:/,''));}
 const recovery=time=>(record.waterings??[]).reduce((sum,w)=>sum+(w.at<=at&&w.at<time?(w.recoveryHours??0)*HOUR:0),0);
 const end=at+recovery(Infinity),removed=new Set();
 const events=(record.cuts??[]).filter(c=>Number.isFinite(c.at)&&c.at<=at).map((c,i)=>({...c,at:c.at+recovery(c.at),seq:c.seq??i})).sort((a,b)=>a.at-b.at||a.seq-b.seq);
 const children=id=>[...live.values()].filter(n=>n.parent===id);
 function queue(key,scope,time,target){if(!jobs.has(key))jobs.set(key,{key,...scope,target,started:time,next:time+HOUR});}
 function check(time,affected){
  for(const zone of zones){const total=[...live.values()].filter(n=>n.pruningLevel===1&&n.zoneId===zone.id).length;
   if(total<zone.low)queue(zone.id,{zoneId:zone.id},time,zone.target);
  }
  if(affected){const parent=live.get(affected);if(parent&&parent.pruningLevel===1&&children(parent.id).length<2)queue(parent.id,{parentId:parent.id,zoneId:parent.zoneId},Math.max(time,parent.readyAt??time),2);}
 }
 function spawn(job,time){
  const zone=zones.find(z=>z.id===job.zoneId),level=job.parentId?live.get(job.parentId).pruningLevel+1:1;
  const key=`state-growth:${serial}`,r=(i,p)=>sample(seed,`${key}:${i}`,p);
  const candidates=[];
  for(let i=0;i<16;i++){
   const support=job.parentId?null:zone.supports[Math.floor(r(i,'support')*zone.supports.length)];
   const parent=live.get(job.parentId??support.parentId),t=job.parentId?.48+r(i,'attach')*.42:clamp(support.t+(r(i,'attach')-.5)*.16,.08,.96);
   const start=pointOn(parent,t),model=level===1?zone.members[Math.floor(r(i,'model')*zone.members.length)]:parent;
   const heading=Math.atan2(model.ey-model.y,model.ex-model.x),angle=heading+(r(i,'angle')-.5)*(level===1?.9:1.3);
   const length=level===1?clamp(Math.hypot(model.ex-model.x,model.ey-model.y)*(.72+r(i,'length')*.25),24,115):clamp(Math.hypot(parent.ex-parent.x,parent.ey-parent.y)*(.4+r(i,'length')*.15),12,46);
   const ex=start.x+Math.cos(angle)*length,ey=start.y+Math.sin(angle)*length;
   let space=80;for(const other of live.values()){if(other.id===parent.id||other.pruningLevel===0)continue;space=Math.min(space,Math.hypot(ex-other.ex,ey-other.ey));}
   const b=scaffold.applicationFrame,inside=ex>b.x+45&&ex<b.x+b.width-45&&ey>b.y+45&&ey<b.y+b.height-45;
   const aboveSoil=record.config.preset==='cascade'||ey<scaffold.root.y-20;
   candidates.push({parent,t,start,ex,ey,score:space+r(i,'jitter')*4+(inside&&aboveSoil?0:-1000)});
  }
  candidates.sort((a,b)=>b.score-a.score);const c=candidates[0],b=scaffold.applicationFrame;
  const ex=clamp(c.ex,b.x+45,b.x+b.width-45),ey=clamp(c.ey,b.y+45,record.config.preset==='cascade'?b.y+b.height-45:scaffold.root.y-25);
  const id=`sprout:${serial++}`,dx=ex-c.start.x,dy=ey-c.start.y;
  const width=clamp((c.parent.width+(c.parent.tipWidth-c.parent.width)*c.t)*.52,.9,level===1?9:4);
  const template=scaffold.clusters.find(n=>n.pad===c.parent.pad)??scaffold.clusters.find(n=>n.pad===zone.members[0].pad)??scaffold.clusters[0];
  const node={id,key:id,parent:c.parent.id,role:level===1?'primary':'twig',pruningLevel:level,branchOrder:level,
   zoneId:zone.id,pad:template.pad,z:template.z,attachment:c.t,x:c.start.x,y:c.start.y,ex,ey,
   cx1:c.start.x+dx*.32,cy1:c.start.y+dy*.26+2,cx2:c.start.x+dx*.72,cy2:c.start.y+dy*.8+2,
   width,tipWidth:width*.32,born:-100,duration:1,bornAt:time,readyAt:time+(level===1?12:8)*HOUR,regrown:true,leafTemplate:template};
  live.set(id,node);
  if(level<3)queue(id,{parentId:id,zoneId:zone.id},node.readyAt,2);
 }
 function advance(time){
  while(true){
   const job=[...jobs.values()].filter(j=>j.next<=time).sort((a,b)=>a.next-b.next||a.started-b.started||a.key.localeCompare(b.key))[0];if(!job)break;
   if(job.parentId&&!live.has(job.parentId)){jobs.delete(job.key);continue;}
   const current=job.parentId?children(job.parentId).length:[...live.values()].filter(n=>n.pruningLevel===1&&n.zoneId===job.zoneId).length;
   if(current>=job.target){jobs.delete(job.key);continue;}
   spawn(job,job.next);if(current+1>=job.target)jobs.delete(job.key);else job.next+=2*HOUR;
  }
 }
 for(const cut of events){
  advance(cut.at);const node=live.get(cut.branchId);if(!node||![1,2].includes(node.pruningLevel))continue;
  const family=branchFamily([...live.values()],node.id);for(const id of family){removed.add(id);live.delete(id);jobs.delete(id);}
  check(cut.at,node.parent);
 }
 advance(end);
 return {live,original,removed,jobs:[...jobs.values()],end,zones};
}

export function applyRecovery(tree,scaffold,record,at,layout=scaffold){
 const plan=recoveryPlan(scaffold,record,at,layout),levels=branchLevels(scaffold.nodes),mapped=new Map();
 tree.nodes=tree.nodes.filter(n=>!plan.removed.has(n.id)).map(n=>({...n,pruningLevel:levels.get(n.id)}));
 tree.clusters=tree.clusters.filter(c=>!plan.removed.has(c.node));tree.buds=tree.buds.filter(c=>!plan.removed.has(c.node));
 tree.nodes.forEach(n=>mapped.set(n.id,n));
 const scale=.55+.45*smooth(tree.progress),thickness=(.04+.96*tree.progress**1.3)*smooth(tree.progress/.018);
 for(const n of plan.live.values()){
  if(!Number.isFinite(n.bornAt))continue;
  const parent=mapped.get(n.parent);if(!parent)continue;
  const age=(plan.end-n.bornAt)/HOUR,g=smooth((plan.end-n.bornAt)/(n.readyAt-n.bornAt))*Math.min(1,parent.growth??1);
  const anchor=pointOn(parent,n.attachment),{leafTemplate,bornAt,readyAt,...properties}=n;
  const node={...properties,x:anchor.x,y:anchor.y,growth:g,width:n.width*thickness*(.15+.85*g),tipWidth:n.tipWidth*thickness*(.15+.85*g)};
  for(const [x,y]of [['cx1','cy1'],['cx2','cy2'],['ex','ey']]){node[x]=anchor.x+(n[x]-n.x)*scale*g;node[y]=anchor.y+(n[y]-n.y)*scale*g;}
  mapped.set(n.id,node);if(g<=0)continue;tree.nodes.push(node);
  const leafAmount=Math.min(smooth((age-3)/18),tree.progress**3);
  if(leafAmount>0){const size=Math.sqrt(leafAmount)*scale;tree.clusters.push({...leafTemplate,node:n.id,key:`leaf:${n.id}`,x:node.ex,y:node.ey-3*size,
   rx:Math.min(32,leafTemplate.rx)*size,ry:Math.min(22,leafTemplate.ry)*size,leafAmount,born:-100,duration:1,crownAge:clamp(age/96)});}
 }
 tree.recovery=plan.jobs.flatMap(job=>{
  const zone=plan.zones.find(z=>z.id===job.zoneId),support=job.parentId?{parentId:job.parentId,t:.7}:zone.supports[0],parent=mapped.get(support.parentId);
  if(!parent||parent.growth<=0)return [];
  const p=pointOn(parent,support.t);return [{key:job.key,node:parent.id,x:p.x,y:p.y,level:job.parentId?(parent.pruningLevel??1)+1:1,hours:Math.max(0,(job.next-plan.end)/HOUR)}];
 });
 return tree;
}
